CIRCUITPY_WEB_API_PORT=8080
CIRCUITPY_WEB_API_PASSWORD="aVycHcYPAD3eYa"
CIRCUITPY_WEB_INSTANCE_NAME="challenger_rp2040_wifi_ble_board_1"
CIRCUITPY_BLE_NAME="challenger_rp2040_wifi_ble_board_1"

CIRCUITPY_WIFI_SSID="BT-RMCMPK"
CIRCUITPY_WIFI_PASSWORD="aVycHcYPAD3eYa"
